export const siteConfig = {
  name: "개발자 솔짜미|DEV ZZAME",
  title: "개발자 솔짜미|DEV ZZAME",
  roleLabel: "Fullstack Developer",
  description: "웹 풀스택 개발자 강한솔의 개인 홈페이지 입니다.",
  siteUrl: "https://devzzame.com",
  locale: "ko_KR",
  email: "dev.zzame@gmail.com",
  githubUrl: "https://github.com/DEVZZAME",
  blogUrl: "https://velog.io/@dev_zzame",
  keywords: [
    "강한솔",
    "개발자 솔짜미",
    "DEV ZZAME",
    "풀스택 개발자",
    "포트폴리오",
    "Fullstack Developer",
    "Prisma",
    "MariaDB",
    "Next.js",
    "이커머스 정산",
    "데이터 파이프라인",
  ],
} as const;
