export const siteConfig = {
  name: "개발자 솔짜미|DEV ZZAME",
  title: "개발자 솔짜미|DEV ZZAME",
  roleLabel: "Back-end Developer",
  description: "데이터 흐름을 설계하고 서비스로 구현하는 백엔드 개발자 강한솔의 포트폴리오 사이트",
  siteUrl: "https://devzzame.com",
  locale: "ko_KR",
  email: "dev.zzame@gmail.com",
  githubUrl: "https://github.com/DEVZZAME",
  blogUrl: "https://velog.io/@dev_zzame",
  keywords: [
    "강한솔",
    "개발자 솔짜미",
    "DEV ZZAME",
    "백엔드 개발자",
    "포트폴리오",
    "Backend Developer",
    "Prisma",
    "MariaDB",
    "Next.js",
    "이커머스 정산",
    "데이터 파이프라인",
  ],
} as const;
